/**:
  # Shared parameters
  ros__parameters:
    node_manifest:
      - auto_apms_behavior_codec_examples::goto

  # Individual node parameters
  tree_decoder_publisher:
    ros__parameters:
      encoded_in_topic: "serialized_tree_in"
      xml_out_topic: "xml_out"
  behavior_tree_encoder:
    ros__parameters:
      xml_in_topic: "xml_in"
      encoded_out_topic: "serialized_tree_out"
