auto_apms_behavior_codec::decoder_executor_params:
  executor_command_in_topic:
    type: string
    default_value: "executor_command"
    read_only: true
    description: Topic name for incoming executor command messages.

  feedback_out_topic:
    type: string
    default_value: "executor_feedback_out"
    read_only: true
    description: Topic name for publishing executor feedback messages.

  feedback_rate:
    type: double
    default_value: 0.5
    read_only: true
    description: Maximum rate (Hz) at which executor is publishing feedback.
    validation:
      gt<>: [0.0]


