auto_apms_behavior_codec::decoder_base_params:
  node_manifest:
    type: string_array
    default_value: []
    read_only: true
    description: List of node manifest resource identities used to build the dictionary. If empty, all registered node manifests will be used.

  encoded_in_topic:
    type: string
    default_value: "serialized_tree_in"
    read_only: true
    description: Topic name for incoming encoded messages.
